
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MathGame2.java
 *
 * Created on Mar 4, 2011, 4:12:49 PM
 */

/**
 *
 * @author Saurabh
 */
public class MathGame2 extends javax.swing.JFrame {

    /** Creates new form MathGame2 */
    public MathGame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("A Math Game");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 16));
        jButton1.setMnemonic('c');
        jButton1.setText("Click this button to start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 15));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("       It is a simple mathmatical game. Think about any real \nnumber & enter the operations u want to do with it. The \nnumber should not be in fractions, it may be in decimals \nthough.\n       You can enter values +x,-x,/x,*x; [xεN]\n       You can enter at maximum 10 times & at minimum 3 times, on completion type \"d1\" & click ok.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Calibri", 0, 14));
        jCheckBox1.setMnemonic('d');
        jCheckBox1.setText("Show Details");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Calibri", 0, 14));
        jCheckBox2.setMnemonic('n');
        jCheckBox2.setText("Do not show Details");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jTextArea1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Double A=0.0;
Double z=null;
JOptionPane.showMessageDialog(null, "Think of a number");
String a=JOptionPane.showInputDialog("Enter an operation e.g : +x,-x,/x,*x. [xεN]");
Double x=Double.parseDouble(a.substring(1));
char y=a.charAt(0);
if(y=='+')
    z=A-x;
if(y=='-')
    z=A+x;
if(y=='*')
    z=A/x;
if(y=='/')
    z=A*x;
String a2=JOptionPane.showInputDialog("Enter an operation e.g : +x,-x,/x,*x. [xεN]");
Double x2=Double.parseDouble(a2.substring(1));
char y2=a2.charAt(0);
if(y2=='+')
    z=A-x2;
if(y2=='-')
    z=A+x2;
if(y2=='*')
    z=A/x2;
if(y2=='/')
    z=A*x2;
String a3=JOptionPane.showInputDialog("Enter an operation e.g : +x,-x,/x,*x. [xεN]");
Double x3=Double.parseDouble(a3.substring(1));
char y3=a3.charAt(0);
if(y3=='+')
    z=A-x3;
if(y3=='-')
    z=A+x3;
if(y3=='*')
    z=A/x3;
if(y3=='/')
    z=A*x;
String a4=JOptionPane.showInputDialog("Enter an operation. Type 'd1' if completed");
Double x4=Double.parseDouble(a4.substring(1));
char y4=a4.charAt(0);
if(y4=='+')
    z=A-x4;
if(y4=='-')
    z=A+x4;
if(y4=='*')
    z=A/x4;
if(y4=='/')
    z=A*x4;
if(a4.substring(0).equals("d1"))
{
    Double r=Double.parseDouble(JOptionPane.showInputDialog("Enter the result :-"));
    JOptionPane.showMessageDialog(null, "The number you thought about is "+z);
}



    }//GEN-LAST:event_jButton1ActionPerformed
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
jTextArea1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
jTextArea1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathGame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
