

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * donboscolibrarystore.java
 *
 * Created on 9 Nov, 2010, 7:17:05 AM
 */

/**
 *
 * @author COMPAQ
 */
public class donboscolibrarystore extends javax.swing.JFrame {

    /** Creates new form donboscolibrarystore */
    public donboscolibrarystore() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class Xi iP Project");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial Narrow", 3, 16));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Names of books"));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 140, 140));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial Narrow", 3, 16));
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Name of Authors"));
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 160, 140));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial Narrow", 3, 16));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("ISBN No."));
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 160, 140));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial Narrow", 3, 16));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(javax.swing.BorderFactory.createTitledBorder("Publishers"));
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, 150));

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 3, 16));
        jRadioButton1.setText("ENGLISH FICTION");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 3, 16));
        jRadioButton2.setText("GENERAL KNOWLEDGE");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 3, 16));
        jRadioButton3.setText("PERSONAL MANAGEMENT");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 3, 16));
        jRadioButton4.setText("GEOGRAPHY");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jRadioButton5.setBackground(new java.awt.Color(0, 153, 204));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Comic Sans MS", 3, 16));
        jRadioButton5.setText("COMPUTER SCIENCE");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 3, 36));
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(" DON BOSCO LIBRARY");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 204, 255), null, new java.awt.Color(0, 153, 204)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 70));

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18));
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("-KOKRAJHAR");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
if (jRadioButton1. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. The Nancy Drew"+'\n');
jTextArea1.append("2. The Hardy Boys"+'\n');
jTextArea1.append("3. Bad Dreams"+'\n');
jTextArea1.append("4. Monster Blood III"+'\n');
jTextArea1.append("5. The Stranger"+'\n');
jTextArea1.append("6. Seven O'Clock Tales"+'\n');
jTextArea1.append("7. The Mystery of the Vanished Price"+'\n');
jTextArea1.append("8. Fullhouse  Club Stephanie"+'\n');
jTextArea1.append("9. Jill and the perfect pony");

jTextArea2.append("1. Carolyn Keene"+'\n');
jTextArea2.append("2. Franklin W.Dixon"+'\n');
jTextArea2.append("3. Wendy Cooling"+'\n');
jTextArea2.append("4. R.L. Stine"+'\n');
jTextArea2.append("5. K.A.Applegate"+'\n');
jTextArea2.append("6. Enid Blyton"+'\n');
jTextArea2.append("7. Enid Blyton"+'\n');
jTextArea2.append("8. Kathy Clark"+'\n');
jTextArea2.append("9. Ruby Ferguson");

jTextArea3.append("1. 0-671-79492-2"+'\n');
jTextArea3.append("2. 0-671-04761-2"+'\n');
jTextArea3.append("3. 1-85881-542-8"+'\n');
jTextArea3.append("4. 0-590-48347-2"+'\n');
jTextArea3.append("5. 0-439-01419-0"+'\n');
jTextArea3.append("6. 0-671-79492-2"+'\n');
jTextArea3.append("7. 0-7497-1339-9"+'\n');
jTextArea3.append("8. 0-671-04194-0"+'\n');
jTextArea3.append("9. 0-340-59079-7"+'\n');

jTextArea4.append("1. An Archway paperback, 1994"+'\n');
jTextArea4.append("2. Aladdin paperbacks, 2002"+'\n');
jTextArea4.append("3. Dolphin, 1997"+'\n');
jTextArea4.append("4. Parachute press, 1995"+'\n');
jTextArea4.append("5. Katherine Applegate, 1997"+'\n');
jTextArea4.append("6. Mammoth, 1997"+'\n');
jTextArea4.append("7. Mammoth, 2004"+'\n');
jTextArea4.append("8. Pocket Books, 2001"+'\n');
jTextArea4.append("9. Knight Publications Books, 2002"+'\n');





        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
if (jRadioButton2. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. Year Book TM"+'\n');
jTextArea1.append("2. Aids in  Asia"+'\n');
jTextArea1.append("3. Inventions,Inventors & Discoveries"+'\n');
jTextArea1.append("4. The Be-happy"+'\n');
jTextArea1.append("5. Family Homepathic medicines"+'\n');
jTextArea1.append("6. Noble Prize winners in Economics"+'\n');
jTextArea1.append("7. Career's G.K. handbook"+'\n');
jTextArea1.append("8. Manorama Year Book 2003"+'\n');
jTextArea1.append("9. Manorama Year Book 2004");

jTextArea2.append("1. P.S.Bright"+'\n');
jTextArea2.append("2. Jai P. Narain "+'\n');
jTextArea2.append("3. P.K.Banarjee"+'\n');
jTextArea2.append("4. Robert H.Schuller"+'\n');
jTextArea2.append("5. Dr. M.B.Panos,M.D. Jane Heimlich"+'\n');
jTextArea2.append("6. Dr. Gagan Jain,D.Litt"+'\n');
jTextArea2.append("7. P.S.Bright"+'\n');
jTextArea2.append("8. K.M.Mathew"+'\n');
jTextArea2.append("9. K.M.Mathew");

jTextArea3.append("1. 81-7199-042-8"+'\n');
jTextArea3.append("2. 0-7619-3244-0"+'\n');
jTextArea3.append("3. 81-87718-74-9"+'\n');
jTextArea3.append("4. 81-222-0132-6"+'\n');
jTextArea3.append("5. 81-222-0081-8"+'\n');
jTextArea3.append("6. 978-81-904611-9-1"+'\n');
jTextArea3.append("7. 789-67-228911-1"+'\n');
jTextArea3.append("8. 81-900461-8-7"+'\n');
jTextArea3.append("9. 0542-5778"+'\n');

jTextArea4.append("1. Bright careers institution, 1999"+'\n');
jTextArea4.append("2. Sage Publications, 2004"+'\n');
jTextArea4.append("3. Arora book comapany, 2003"+'\n');
jTextArea4.append("4. Orient Paperbacks, 2001"+'\n');
jTextArea4.append("5. Orient Paperbacks, 1983"+'\n');
jTextArea4.append("6. Three ess publications, 1997"+'\n');
jTextArea4.append("7. Bright careers institution, 2004"+'\n');
jTextArea4.append("8. Malayala Manorama, 2003"+'\n');
jTextArea4.append("9. Malayala Manorama, 2004"+'\n');
















        // TODO add your handling code here:
    }

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {
if (jRadioButton3. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. Wings of Fire "+'\n');
jTextArea1.append("2. Freedom is not free"+'\n');
jTextArea1.append("3. True Polar Adventure"+'\n');
jTextArea1.append("4. Authority- Its Use and Abuse"+'\n');
jTextArea1.append("5. Babudom-Catacombs of Indian Bureaucracy"+'\n');
jTextArea1.append("6. You and your career"+'\n');
jTextArea1.append("7. He can who thinks he can"+'\n');
jTextArea1.append("8. Accidental Entrepreneur"+'\n');
jTextArea1.append("9. Seven on Life's Adventure");

jTextArea2.append("1. A.P.J.Abdul Kalam"+'\n');
jTextArea2.append("2. Shiv Khera "+'\n');
jTextArea2.append("3. Paul Doswell "+'\n');
jTextArea2.append("4. C.P.Varkey"+'\n');
jTextArea2.append("5. S.Mohanty"+'\n');
jTextArea2.append("6. Joe D. Pereira"+'\n');
jTextArea2.append("7. John Parankimalil"+'\n');
jTextArea2.append("8. Puneet Shrivastasva"+'\n');
jTextArea2.append("9. Christine Gomez");

jTextArea3.append("1. 81-7371-146-1"+'\n');
jTextArea3.append("2. 1403-92273-x"+'\n');
jTextArea3.append("3. 0-7460-5193-x"+'\n');
jTextArea3.append("4. 81-7109-413-9"+'\n');
jTextArea3.append("5. 81-291-0383-4"+'\n');
jTextArea3.append("6. 81-7108-176-2"+'\n');
jTextArea3.append("7. 0333-936713"+'\n');
jTextArea3.append("8. 81-291-0342-7"+'\n');
jTextArea3.append("9. 81-7176-189-5"+'\n');

jTextArea4.append("1. Universities Press, 1999"+'\n');
jTextArea4.append("2. Macmillan India ltd., 2004"+'\n');
jTextArea4.append("3. Usborne, 2002"+'\n');
jTextArea4.append("4. St.Pauls, 2000"+'\n');
jTextArea4.append("5. Rupa Co., 2004"+'\n');
jTextArea4.append("6. St.Pauls, 1997"+'\n');
jTextArea4.append("7. Macmillan India ltd, 2000"+'\n');
jTextArea4.append("8. Rupa Co., 2004"+'\n');
jTextArea4.append("9. Pauline Publications, 2003"+'\n');



        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
if (jRadioButton5. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. BBC Programs in BASIC "+'\n');
jTextArea1.append("2. Games Collection for the BBC Micro"+'\n');
jTextArea1.append("3. Information Practices XI"+'\n');
jTextArea1.append("4. Introductoy Information Technology X"+'\n');
jTextArea1.append("5. Fortram IV for computers"+'\n');
jTextArea1.append("6. Dreamlands Illustrated Computer Encyclopedia"+'\n');
jTextArea1.append("7. Web programming");


jTextArea2.append("1. Derrick Daines"+'\n');
jTextArea2.append("2. Bryn Phillips "+'\n');
jTextArea2.append("3. Sumita Arora "+'\n');
jTextArea2.append("4. Sumita Arora"+'\n');
jTextArea2.append("5. P.N.Arora,Harjeet Singh"+'\n');
jTextArea2.append("6. Phashant Gupta "+'\n');
jTextArea2.append("7. Kris Jams A.");


jTextArea3.append("1. 0-408-01415-6"+'\n');
jTextArea3.append("2. 0-7216-0621-1"+'\n');
jTextArea3.append("3. 81-7700-001-2"+'\n');
jTextArea3.append("4. 81-7700-065-9"+'\n');
jTextArea3.append("5. 81-219-0050-6"+'\n');
jTextArea3.append("6. 81-7301-481-7"+'\n');
jTextArea3.append("7. 81-7170-362-3");


jTextArea4.append("1. Newnes technology Books., 1984"+'\n');
jTextArea4.append("3. Century Communications London,  1984"+'\n');
jTextArea4.append("2. Dhanpat Rai & Co., 2003"+'\n');
jTextArea4.append("4. Dhanpat Rai & Co., 2005"+'\n');
jTextArea4.append("5. Sultan Chand & company Ltd., 2005"+'\n');
jTextArea4.append("6. Dreamland Publications, 2000"+'\n');
jTextArea4.append("7. Frank bros. & Co., 1996"+'\n');
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
if (jRadioButton3. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. Wings of Fire "+'\n');
jTextArea1.append("2. Freedom is not free"+'\n');
jTextArea1.append("3. True Polar Adventure"+'\n');
jTextArea1.append("4. Authority- Its Use and Abuse"+'\n');
jTextArea1.append("5. Babudom-Catacombs of Indian Bureaucracy"+'\n');
jTextArea1.append("6. You and your career"+'\n');
jTextArea1.append("7. He can who thinks he can"+'\n');
jTextArea1.append("8. Accidental Entrepreneur"+'\n');
jTextArea1.append("9. Seven on Life's Adventure");

jTextArea2.append("1. A.P.J.Abdul Kalam"+'\n');
jTextArea2.append("2. Shiv Khera "+'\n');
jTextArea2.append("3. Paul Doswell "+'\n');
jTextArea2.append("4. C.P.Varkey"+'\n');
jTextArea2.append("5. S.Mohanty"+'\n');
jTextArea2.append("6. Joe D. Pereira"+'\n');
jTextArea2.append("7. John Parankimalil"+'\n');
jTextArea2.append("8. Puneet Shrivastasva"+'\n');
jTextArea2.append("9. Christine Gomez");

jTextArea3.append("1. 81-7371-146-1"+'\n');
jTextArea3.append("2. 1403-92273-x"+'\n');
jTextArea3.append("3. 0-7460-5193-x"+'\n');
jTextArea3.append("4. 81-7109-413-9"+'\n');
jTextArea3.append("5. 81-291-0383-4"+'\n');
jTextArea3.append("6. 81-7108-176-2"+'\n');
jTextArea3.append("7. 0333-936713"+'\n');
jTextArea3.append("8. 81-291-0342-7"+'\n');
jTextArea3.append("9. 81-7176-189-5"+'\n');

jTextArea4.append("1. Universities Press, 1999"+'\n');
jTextArea4.append("2. Macmillan India ltd., 2004"+'\n');
jTextArea4.append("3. Usborne, 2002"+'\n');
jTextArea4.append("4. St.Pauls, 2000"+'\n');
jTextArea4.append("5. Rupa Co., 2004"+'\n');
jTextArea4.append("6. St.Pauls, 1997"+'\n');
jTextArea4.append("7. Macmillan India ltd, 2000"+'\n');
jTextArea4.append("8. Rupa Co., 2004"+'\n');
jTextArea4.append("9. Pauline Publications, 2003"+'\n');



        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
if (jRadioButton4. isSelected()==true)
    jTextArea1.setText("");
jTextArea1.append("1. Kuwait "+'\n');
jTextArea1.append("2. Korea"+'\n');
jTextArea1.append("3. Mongolia"+'\n');
jTextArea1.append("4. Democartic Republic of Congo"+'\n');
jTextArea1.append("5. Jamaica"+'\n');
jTextArea1.append("6. Croatia"+'\n');
jTextArea1.append("7. Somalia");


jTextArea2.append("1. Maria O'Shea"+'\n');
jTextArea2.append("2. Till Du Bois "+'\n');
jTextArea2.append("3. Geek Cheng Pang "+'\n');
jTextArea2.append("4. Jay Heale"+'\n');
jTextArea2.append("5. Sean Sheehan"+'\n');
jTextArea2.append("6. Robert Cooper "+'\n');
jTextArea2.append("7. Susan M. Hassig");


jTextArea3.append("1. 981-204-859-6"+'\n');
jTextArea3.append("2. 981-204-4-582"+'\n');
jTextArea3.append("3. 981-204-866-9"+'\n');
jTextArea3.append("4. 981-204-862-6"+'\n');
jTextArea3.append("5. 981-204-538-4"+'\n');
jTextArea3.append("6. 981-232-105-5"+'\n');
jTextArea3.append("7. 981-204-710-7");


jTextArea4.append("1. Times Books Int., 1999"+'\n');
jTextArea4.append("3. Times Books Int., 1994, 1999"+'\n');
jTextArea4.append("2. Times Books Int., 1999"+'\n');
jTextArea4.append("4. Times Books Int., 1999"+'\n');
jTextArea4.append("5. Times Books Int., 1996"+'\n');
jTextArea4.append("6. Times Books Int., 2000"+'\n');
jTextArea4.append("7. Times Books Int., 1997"+'\n');


        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donboscolibrarystore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables

}
